import { MoveDownLeft, MoveUpRight } from "lucide-react";

export const Stats = () => (
  <div className="w-full py-20 lg:py-40" data-aos="fade-right">
    <div className="container mx-auto">
      <div className="grid text-left grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 w-full gap-4 lg:gap-8">
        {/* Stat 1 */}
        <div className="flex gap-0 flex-col justify-between p-6 border rounded-md">
          <MoveUpRight className="w-4 h-4 mb-10 text-primary" />
          <h2 className="text-4xl tracking-tighter max-w-xl text-left font-regular flex flex-row gap-4 items-end">
            12,000
            <span className="text-muted-foreground text-sm tracking-normal">
              +15.3%
            </span>
          </h2>
          <p className="text-base leading-relaxed tracking-tight text-muted-foreground max-w-xl text-left">
            Scheduled posts per month
          </p>
        </div>
        {/* Stat 2 */}
        <div className="flex gap-0 flex-col justify-between p-6 border rounded-md">
          <MoveDownLeft className="w-4 h-4 mb-10 text-destructive" />
          <h2 className="text-4xl tracking-tighter max-w-xl text-left font-regular flex flex-row gap-4 items-end">
            2,350
            <span className="text-muted-foreground text-sm tracking-normal">
              -5.6%
            </span>
          </h2>
          <p className="text-base leading-relaxed tracking-tight text-muted-foreground max-w-xl text-left">
            Posts requiring manual edits
          </p>
        </div>
        {/* Stat 3 */}
        <div className="flex gap-0 flex-col justify-between p-6 border rounded-md">
          <MoveUpRight className="w-4 h-4 mb-10 text-success" />
          <h2 className="text-4xl tracking-tighter max-w-xl text-left font-regular flex flex-row gap-4 items-end">
            $42,000
            <span className="text-muted-foreground text-sm tracking-normal">
              +12%
            </span>
          </h2>
          <p className="text-base leading-relaxed tracking-tight text-muted-foreground max-w-xl text-left">
            Revenue generated by automated campaigns
          </p>
        </div>
        {/* Stat 4 */}
        <div className="flex gap-0 flex-col justify-between p-6 border rounded-md">
          <MoveUpRight className="w-4 h-4 mb-10 text-primary" />
          <h2 className="text-4xl tracking-tighter max-w-xl text-left font-regular flex flex-row gap-4 items-end">
            85%
            <span className="text-muted-foreground text-sm tracking-normal">
              +3%
            </span>
          </h2>
          <p className="text-base leading-relaxed tracking-tight text-muted-foreground max-w-xl text-left">
            Engagement rate on LinkedIn
          </p>
        </div>
      </div>
    </div>
  </div>
);
